import { Activity, BatteryCharging, Box, Coins, HeartPulse, Pickaxe, RotateCcw, Sparkles, Trophy, Zap } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import type { CSSProperties } from 'react'
import miningAtlas from '../assets/mining/voxel-mining-atlas.png'
import pickaxeImage from '../assets/mining/nexus-voxel-pickaxe.png'
import { GlowButton } from '../components/ui/GlowButton'
import { useMemberStore } from '../store/useMemberStore'
import { formatMoney } from '../utils/format'

interface Tool { id:string; name:string; price:number; hp:number; power:number; size:number; tone:'pink'|'amber'|'violet' }
interface Mineral { id:string; name:string; value:number; texture:string }
type BlockKind = 'dirt'|'stone'|'deep'|'copper'|'quartz'|'gold'|'violet'|'plasma'|'void'|'repair'|'mega'|'tnt'
interface RunState { status:'idle'|'running'|'complete'; hp:number; maxHp:number; depth:number; row:number; value:number; hits:number; size:number; combo:number; lastEvent:string; mineralCounts:Record<string,number>; hitIndex:number; brokenIndices:number[]; minedIndices:number[]; column:number; x:number; velocity:number; airTicks:number; strikeStage:number; sideStreak:number; target:BlockKind }
const tools:Tool[]=[{id:'spark',name:'WOOD PICK',price:5,hp:72,power:1,size:1,tone:'pink'},{id:'neon',name:'IRON PICK',price:15,hp:125,power:2,size:1.12,tone:'violet'},{id:'plasma',name:'GOLD PICK',price:30,hp:190,power:3,size:1.28,tone:'amber'},{id:'titan',name:'NEXUS PICK',price:60,hp:290,power:5,size:1.48,tone:'pink'}]
const minerals:Mineral[]=[{id:'copper',name:'COPPER BYTE',value:1.2,texture:'copper'},{id:'quartz',name:'NEON QUARTZ',value:3.5,texture:'quartz'},{id:'gold',name:'GOLD SHARD',value:8,texture:'gold'},{id:'violet',name:'VIOLET CRYSTAL',value:16,texture:'violet'},{id:'plasma',name:'PLASMA GEM',value:32,texture:'plasma'},{id:'void',name:'VOID DIAMOND',value:75,texture:'void'}]
const emptyRun=(tool:Tool):RunState=>({status:'idle',hp:tool.hp,maxHp:tool.hp,depth:0,row:0,value:0,hits:0,size:tool.size,combo:0,lastEvent:'SELECT A PICKAXE TO INITIALIZE',mineralCounts:{},hitIndex:-1,brokenIndices:[],minedIndices:[],column:3,x:3,velocity:0,airTicks:5,strikeStage:0,sideStreak:0,target:baseKindAt(3)})
const getZone=(d:number)=>d<220?'SURFACE LAYER':d<520?'STONE VEIN':d<900?'GOLD FAULT':d<1200?'VIOLET ABYSS':'ENDLESS NEXUS'
const baseKindAt=(i:number):BlockKind=>{const row=Math.floor(i/8),d=row*44,p=(i*37+row*19)%97;if(p===7||p===73)return'tnt';if(p===11||p===31||p===53||p===84||p===94)return'repair';if(p===29||p===59)return'mega';if(p===3||p===18||p===44||p===64)return'copper';if(p===9||p===25||p===35||p===70)return'quartz';if((p===22||p===48||p===61)&&d>260)return'gold';if((p===40||p===79||p===82)&&d>540)return'violet';if((p===67||p===76||p===88)&&d>880)return'plasma';if((p===91||p===96)&&d>1300)return'void';return d<180?'dirt':d<750?'stone':'deep'}
const craterAt=(i:number,tnt=false)=>{if(!tnt)return[i];const row=Math.floor(i/8),col=i%8,cells:number[]=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const c=col+dx,r=row+dy;if(c>=0&&c<8&&r>=0)cells.push(r*8+c)}return cells}
const atlasStyle={'--mining-atlas':`url(${miningAtlas})`} as CSSProperties

export function CoreDropPage(){
 const{wallet,withdrawFunds,depositFunds}=useMemberStore();const[selectedId,setSelectedId]=useState('neon');const selected=tools.find(t=>t.id===selectedId)??tools[1];const[run,setRun]=useState<RunState>(()=>emptyRun(selected));const[settled,setSettled]=useState(false)
 const totalRows=Math.max(34,Math.floor(run.depth/44)+18)
 const blocks=useMemo(()=>Array.from({length:totalRows*8},(_,i)=>{const kind=baseKindAt(i);return{kind,active:i===run.hitIndex,broken:run.brokenIndices.includes(i),mined:run.minedIndices.includes(i)}}),[totalRows,run.hitIndex,run.brokenIndices,run.minedIndices])
 useEffect(()=>{if(run.status!=='running')return;const timer=window.setInterval(()=>setRun(current=>{
  let velocity=Math.max(-.72,Math.min(.72,current.velocity*.62+(Math.random()-.5)*.7)),x=current.x+velocity*.42;const left=current.column-.38,right=current.column+.38;if(x<left||x>right){x=Math.max(left,Math.min(right,x));velocity*=-.82}
  if(current.airTicks>0)return{...current,x,velocity,airTicks:current.airTicks-1,lastEvent:current.airTicks===1?'TERRAIN CONTACT // BRACE':'GRAVITY DROP // PICKAXE SWAY'}
  const column=current.column,zone=Math.floor(current.depth/320),hardness=9+zone*3,damage=Math.max(3,Math.round(hardness/selected.power*(1.8/Math.max(1,current.size)))),hp=Math.max(0,current.hp-damage),strikeStage=current.strikeStage+1,row=current.row,hitIndex=row*8+column
  if(strikeStage<3&&hp>0)return{...current,hp,x,velocity,hitIndex,brokenIndices:[],strikeStage,hits:current.hits+1,lastEvent:`CRACKING ${current.target.toUpperCase()} // ${strikeStage}/3`}
  let size=current.size,repairedHp=hp,value=current.value,event='STONE CLEARED // NO VALUE';const counts={...current.mineralCounts},mineral=minerals.find(m=>m.texture===current.target),isTnt=current.target==='tnt',crater=craterAt(hitIndex,isTnt)
  if(current.target==='repair'){const repair=Math.round(current.maxHp*.2);repairedHp=Math.min(current.maxHp,repairedHp+repair);event=`REPAIR ORE // +${repair} HP`}else if(current.target==='mega'){size=Math.min(2,size+.18);event='GIANT ORE // PICKAXE RANGE UP'}else if(isTnt){let blastValue=0;crater.forEach(cell=>{const found=minerals.find(m=>m.texture===baseKindAt(cell));if(found){blastValue+=found.value;counts[found.id]=(counts[found.id]??0)+1}});value+=blastValue;event=`TNT BLAST // ${crater.length} BLOCKS${blastValue?` // +${formatMoney(blastValue)}`:''}`}else if(mineral){const multiplier=Math.random()>.94?3:1,found=mineral.value*multiplier*Math.max(1,size);value+=found;counts[mineral.id]=(counts[mineral.id]??0)+1;event=`${multiplier>1?'RICH ':''}${mineral.name} // +${formatMoney(found)}`}
  const mined=[...new Set([...current.minedIndices,...crater])],sideOptions=[column-1,column+1].filter(c=>c>=0&&c<8&&!mined.includes(row*8+c)),goSide=current.sideStreak<2&&sideOptions.length>0&&Math.random()<.58,nextColumn=goSide?sideOptions[Math.floor(Math.random()*sideOptions.length)]:column,nextRow=goSide?row:row+1,nextIndex=nextRow*8+nextColumn,depth=Math.max(current.depth,nextRow*44),nextTarget=baseKindAt(nextIndex);return{...current,status:repairedHp<=0?'complete':'running',hp:repairedHp,depth,row:nextRow,value,hits:current.hits+1,size,combo:current.combo+crater.length,lastEvent:`${event} // ${goSide?'SIDE RICOCHET':'GRAVITY DROP'}`,mineralCounts:counts,hitIndex:-1,brokenIndices:crater,minedIndices:mined,column:nextColumn,x:nextColumn,velocity:(nextColumn-column)*.62,strikeStage:0,sideStreak:goSide?current.sideStreak+1:0,target:nextTarget}
 }),440);return()=>window.clearInterval(timer)},[run.status,selected.power])
 useEffect(()=>{if(run.status==='complete'&&!settled){setSettled(true);if(run.value>0)depositFunds(run.value,'NEXUS: CORE DROP extraction')}},[run.status,run.value,settled,depositFunds])
 const chooseTool=(t:Tool)=>{if(run.status==='running')return;setSelectedId(t.id);setRun(emptyRun(t));setSettled(false)}
 const start=()=>{if(!withdrawFunds(selected.price,'NEXUS: CORE DROP tool deployment')){setRun(c=>({...c,lastEvent:'INSUFFICIENT WALLET SIGNAL'}));return}setSettled(false);setRun({...emptyRun(selected),status:'running',lastEvent:'PICKAXE RELEASED // GRAVITY ONLINE'})},reset=()=>{setRun(emptyRun(selected));setSettled(false)}
 const cameraRow=Math.max(0,run.row-7),visibleRow=run.row-cameraRow,surfaceProgress=Math.min(1,run.depth/300)
 const toolTop=run.airTicks>0?`${2+(5-run.airTicks)*2.8}%`:`calc(18% + ${visibleRow} * var(--block-row) - 25px)`
 const worldStyle={...atlasStyle,'--camera-row':cameraRow,'--total-rows':totalRows,'--surface-progress':surfaceProgress,'--pick-tilt':`${run.velocity*34}deg`} as CSSProperties
 return <div className="core-drop" style={worldStyle}><header className="core-drop__header"><div><span>NODE GAME // 001</span><h1>NEXUS: <em>CORE DROP</em></h1><p>AUTOMATED VOXEL EXTRACTION · ENDLESS FRONTEND SIMULATION</p></div><div><span>MEMBER WALLET</span><strong>{formatMoney(wallet.balance)}</strong></div></header>
 <section className="core-drop__layout"><aside className="tool-bay"><div className="mining-panel-title"><Pickaxe/><span>MINING TOOL BAY</span></div>{tools.map(t=><button key={t.id} className={`tool-option tool-option--${t.tone} ${selectedId===t.id?'active':''}`} onClick={()=>chooseTool(t)} disabled={run.status==='running'}><div><Pickaxe/></div><span><strong>{t.name}</strong><small>{formatMoney(t.price)} DEPLOYMENT</small></span><i>HP {t.hp}<b>POW {t.power}</b></i></button>)}<div className="tool-spec"><span>TOOL SIZE<strong>{selected.size.toFixed(2)}x</strong></span><span>STARTING HP<strong>{selected.hp}</strong></span><span>BREAK POWER<strong>{selected.power}</strong></span></div><GlowButton tone={selected.tone} onClick={run.status==='complete'?reset:start} disabled={run.status==='running'}>{run.status==='complete'?<><RotateCcw/>NEW DROP</>:<><Zap/>DEPLOY PICK · {formatMoney(selected.price)}</>}</GlowButton></aside>
 <main className={`mine-shaft ${run.status==='running'?'mine-shaft--running':''}`}><div className="mine-shaft__top"><span>DEPTH <strong>{run.depth}M</strong></span><span>{getZone(run.depth)}</span><span>INTEGRITY <strong>{Math.round(run.hp/run.maxHp*100)}%</strong></span></div><div className="mine-world"><div className="mine-sky"><i/><i/><i/><span>DROP ZONE</span></div><div className="depth-lines"><span style={{top:'52%'}}>{run.depth}M</span></div><div className="block-field">{blocks.map((b,i)=><i key={i} className={`mine-block mine-block--${b.kind} ${b.active?`mine-block--hit mine-block--crack-${run.strikeStage}`:''} ${b.broken?'mine-block--broken':''} ${b.mined?'mine-block--mined':''}`}><span/></i>)}</div><div className={`drop-tool ${run.airTicks>0?'drop-tool--falling':'drop-tool--striking'}`} style={{left:`${6.25+run.x*12.5}%`,top:toolTop,transform:`scale(${Math.min(1.18,run.size)}) rotate(var(--pick-tilt))`}}><img key={`${run.airTicks}-${run.hits}`} src={pickaxeImage} alt="Voxel mining pickaxe"/><i/></div><div className="mine-event" key={`${run.hits}-${run.lastEvent}`}>{run.lastEvent}</div></div><div className="integrity-bar"><i style={{width:`${run.hp/run.maxHp*100}%`}}/><span>{run.hp} / {run.maxHp} HP</span></div></main>
 <aside className="extraction-feed"><div className="mining-panel-title"><Activity/><span>LIVE EXTRACTION</span></div><div className="current-haul"><span>CURRENT MINERAL VALUE</span><strong>{formatMoney(run.value)}</strong><small>{run.status==='running'?'MINING IN PROGRESS':run.status==='complete'?'EXTRACTION COMPLETE':'AWAITING DEPLOYMENT'}</small></div><div className="run-metrics"><span><Box/>BLOCKS CLEARED<strong>{run.combo}</strong></span><span><Sparkles/>PICK SIZE<strong>{run.size.toFixed(2)}x</strong></span><span><Trophy/>STRIKES<strong>{run.hits}</strong></span><span><BatteryCharging/>DEPTH<strong>{run.depth}M</strong></span></div><div className="tnt-legend"><b>TNT</b><span>RARE FIND · BLASTS A 3×3 AREA</span></div><div className="mineral-inventory"><span>VALUABLE MINERALS ONLY</span>{minerals.map(m=><div key={m.id}><i className={`mineral-dot mineral-dot--${m.texture}`}/><b>{m.name}</b><strong>{run.mineralCounts[m.id]??0}</strong></div>)}</div>{run.status==='complete'&&<div className="extraction-result"><HeartPulse/><span>TOOL INTEGRITY: 0%</span><h3>EXTRACTION COMPLETE</h3><strong>{formatMoney(run.value)}</strong><small>NET {formatMoney(run.value-selected.price)}</small></div>}</aside></section>
 <footer className="core-drop__footer"><Coins/>ENDLESS SHAFT · MOST BLOCKS HAVE NO VALUE · TNT BLASTS NEARBY ORES · LOCAL DEMO RANDOMNESS</footer></div>
}
