import { AlertTriangle, Eye, EyeOff, KeyRound, Radio, RotateCcw, ShieldCheck, UserRound, Zap } from 'lucide-react'
import { useState } from 'react'
import type { FormEvent } from 'react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { AnimatedBackground } from '../components/layout/AnimatedBackground'
import { useMemberStore } from '../store/useMemberStore'

export function LoginPage() {
  const navigate = useNavigate(); const location = useLocation(); const { login, isAuthenticated } = useMemberStore()
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [signalLost, setSignalLost] = useState(false); const [loading, setLoading] = useState(false)
  const destination = typeof location.state === 'object' && location.state && 'from' in location.state && typeof location.state.from === 'string' ? location.state.from : '/'
  if (isAuthenticated) return <Navigate to="/" replace />
  const submit = (event: FormEvent) => { event.preventDefault(); setLoading(true); window.setTimeout(() => { const valid = login(username.trim(), password); setLoading(false); if (valid) navigate(destination, { replace:true }); else setSignalLost(true) }, 650) }
  return <main className={`login-page ${signalLost ? 'login-page--lost' : ''}`}><AnimatedBackground /><div className="login-page__noise" /><div className="login-topline"><div><Zap size={15} fill="currentColor" /> NEXUS ACCESS NETWORK</div><span>CONNECTION <b>{signalLost ? 'LOST' : 'STANDBY'}</b></span><time>{new Date().toLocaleTimeString('en-MY',{ hour:'2-digit',minute:'2-digit' })}</time></div>
    <section className="login-stage"><div className="login-stage__code">SYS.AUTH // 00-41<br />NODE: MEMBER_GATE<br />ENCRYPTION: MOCK</div><div className="login-panel"><span className="login-panel__cut login-panel__cut--one" /><span className="login-panel__cut login-panel__cut--two" /><div className="login-panel__sweep" /><header><div className="login-logo"><Zap size={24} fill="currentColor" /></div><div><span>MEMBER ACCESS</span><h1>NEXUS</h1></div><i>01</i></header><div className="login-copy"><span><Radio size={12} /> SECURE SIGNAL DETECTED</span><h2>Enter the <em>night grid.</em></h2><p>Identify your member signal to continue.</p></div><form onSubmit={submit}><label><span>MEMBER ACCOUNT</span><div><UserRound size={17} /><input autoFocus autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} placeholder="Enter account" /></div></label><label><span>ACCESS KEY</span><div><KeyRound size={17} /><input type={showPassword ? 'text' : 'password'} autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter access key" /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label><button className="login-submit" disabled={loading}>{loading ? <><Radio size={16} /> SCANNING SIGNAL...</> : <><ShieldCheck size={17} /> CONNECT TO NEXUS</>}</button></form><div className="demo-credentials"><span>DEMO ACCESS</span><button onClick={() => { setUsername('alex@nexus.demo'); setPassword('NEXUS404') }}>ACCOUNT: alex@nexus.demo <b>/</b> KEY: NEXUS404</button></div><footer><span>LOCAL SIMULATION ONLY</span><span>NO REAL AUTHENTICATION</span></footer></div><div className="login-stage__index">ACCESS<br /><strong>00/01</strong></div></section>
    {signalLost && <section className="signal-lost" role="alert"><div className="signal-lost__ghost">404</div><div className="signal-lost__frame"><AlertTriangle /><span>ERROR // AUTH_SIGNAL</span><h2 data-text="SIGNAL NOT FOUND">SIGNAL NOT FOUND</h2><strong>404</strong><p>MEMBER SIGNATURE REJECTED<br />UNKNOWN NODE ATTEMPT DETECTED</p><div className="signal-bars">{Array.from({ length:18 },(_,index) => <i key={index} />)}</div><button onClick={() => { setSignalLost(false); setPassword('') }}><RotateCcw size={15} /> RE-ESTABLISH CONNECTION</button></div></section>}
  </main>
}
