import { Save, UserRound } from 'lucide-react'
import { useState } from 'react'
import type { FormEvent } from 'react'
import { GlowButton } from '../components/ui/GlowButton'
import { NeonCard } from '../components/ui/NeonCard'
import { PageHeading } from '../components/ui/PageHeading'
import { useMemberStore } from '../store/useMemberStore'

export function ProfilePage() { const { profile, updateProfile } = useMemberStore(); const [draft, setDraft] = useState(profile); const [saved, setSaved] = useState(false); const submit = (event: FormEvent) => { event.preventDefault(); updateProfile(draft); setSaved(true) }; return <div><PageHeading eyebrow="MY IDENTITY" title="Shape your" highlight="member profile." description="Prototype profile preferences stored only on this device." icon={UserRound} /><section className="profile-grid"><NeonCard accent="violet" className="identity-card"><div className="identity-avatar">AT<i /></div><span>MEMBER SINCE 2026</span><h3>{profile.name}</h3><p>{profile.id}</p><div><b>VIP 0{profile.vipLevel}</b><b>ONLINE</b></div></NeonCard><NeonCard className="profile-form"><div className="panel-heading"><div><span>PERSONAL PREFERENCES</span><h3>Profile details</h3></div></div><form onSubmit={submit}><div className="form-grid"><label>MEMBER ID<input className="neon-input" value={draft.id} disabled /></label><label>DISPLAY NAME<input className="neon-input" value={draft.name} onChange={(event) => setDraft({ ...draft, name:event.target.value })} /></label><label>EMAIL<input className="neon-input" type="email" value={draft.email} onChange={(event) => setDraft({ ...draft, email:event.target.value })} /></label><label>PHONE<input className="neon-input" value={draft.phone} onChange={(event) => setDraft({ ...draft, phone:event.target.value })} /></label><label>PREFERRED CURRENCY<select className="neon-input" value={draft.currency} onChange={(event) => setDraft({ ...draft, currency:event.target.value })}><option>MYR</option><option>SGD</option><option>USD</option></select></label><label>PREFERRED THEME<select className="neon-input" value={draft.theme} onChange={(event) => setDraft({ ...draft, theme:event.target.value })}><option>Neon Night</option><option>Violet Haze</option><option>Amber Rush</option></select></label></div><GlowButton type="submit"><Save size={15} /> SAVE LOCAL PROFILE</GlowButton>{saved && <span className="saved-label">PROFILE SAVED</span>}</form></NeonCard></section></div> }
