import { Bell, MonitorCog, RotateCcw, Settings, SlidersHorizontal } from 'lucide-react'
import { useState } from 'react'
import { GlowButton } from '../components/ui/GlowButton'
import { NeonCard } from '../components/ui/NeonCard'
import { PageHeading } from '../components/ui/PageHeading'
import { useMemberStore } from '../store/useMemberStore'
import type { PortalTheme } from '../store/useMemberStore'

export function SettingsPage() { const { resetDemo, portalTheme, setPortalTheme } = useMemberStore(); const [confirming, setConfirming] = useState(false); const [notifications, setNotifications] = useState(true); const [motion, setMotion] = useState('High Voltage'); return <div><PageHeading eyebrow="PORTAL CONFIG" title="Tune your" highlight="NEXUS." description="Personalize this local member prototype." icon={Settings} /><section className="settings-grid"><NeonCard className="settings-card"><div className="setting-icon"><MonitorCog /></div><div><span>DISPLAY</span><h3>Theme Mode</h3><p>Changes the lighting profile across the entire portal.</p></div><select className="neon-input" value={portalTheme} onChange={(event) => setPortalTheme(event.target.value as PortalTheme)}><option value="neon-night">Neon Night</option><option value="black-yellow">Black / Yellow</option><option value="violet-haze">Violet Haze</option></select></NeonCard><NeonCard accent="violet" className="settings-card"><div className="setting-icon"><SlidersHorizontal /></div><div><span>MOTION</span><h3>Motion Intensity</h3><p>Control flicker and ambient movement.</p></div><select className="neon-input" value={motion} onChange={(event) => setMotion(event.target.value)}><option>High Voltage</option><option>Balanced</option><option>Reduced</option></select></NeonCard><NeonCard accent="amber" className="settings-card"><div className="setting-icon"><Bell /></div><div><span>ALERTS</span><h3>Notifications</h3><p>Mock promotion and reward alerts.</p></div><button className={`toggle ${notifications ? 'toggle--on' : ''}`} onClick={() => setNotifications(!notifications)}><i /></button></NeonCard><NeonCard className="settings-card system-info"><div><span>LOCAL SIMULATION INFO</span><h3>Prototype Environment</h3></div><dl><div><dt>ENVIRONMENT</dt><dd>LOCAL SIMULATION</dd></div><div><dt>API</dt><dd>NOT CONNECTED</dd></div><div><dt>PAYMENT GATEWAY</dt><dd>MOCK ONLY</dd></div><div><dt>STORAGE</dt><dd>LOCAL BROWSER</dd></div></dl></NeonCard></section><NeonCard accent="amber" className="danger-zone"><div><span>DEMO RESET</span><h3>Reset local member data</h3><p>Restore wallet, transactions, promotions, rewards, profile, and theme to their initial mock values.</p></div><GlowButton tone="amber" onClick={() => setConfirming(true)}><RotateCcw size={15} /> RESET DEMO DATA</GlowButton></NeonCard>{confirming && <div className="modal-backdrop" role="presentation"><NeonCard className="confirm-modal" role="dialog" aria-modal="true"><span>CONFIRM RESET</span><h3>Erase local demo changes?</h3><p>This only resets prototype data stored in your browser.</p><div><GlowButton tone="amber" onClick={() => { resetDemo(); setConfirming(false) }}>YES, RESET</GlowButton><button className="ghost-button" onClick={() => setConfirming(false)}>CANCEL</button></div></NeonCard></div>}</div> }
